

##########################################################
# GET ALL
##########################################################
GET http://127.0.0.1:5000/users
##########################################################
# CREATE USER
##########################################################
POST http://localhost:5000/register
Content-Type: application/json

{
    "nama": "M. Fidyan Fatra Aldino",
    "email": "fatraaldino@gmail.com",
    "password": "password",
}
##########################################################
# GET UUID
##########################################################
GET http://127.0.0.1:5000/users/058c9025fde044bcae63ed6df3343794
##########################################################
# UPDATE USER
##########################################################
PUT http://127.0.0.1:5000/users/058c9025fde044bcae63ed6df3343794
Content-Type: application/json

{
    "nama": "m. fidyan fatra aldino",
    "email": "caca@gmail.com",
    "alamat": "jl. abdul wahab",
    "no_telp": "0896547885",
    "jml_point": 100
}

