

##########################################################
# GET ALL
##########################################################
GET http://127.0.0.1:5000/users
##########################################################
# CREATE USER
##########################################################
POST http://localhost:5000/register
Content-Type: application/json

{
    "nama": "M. Fidyan Fatra Aldino",
    "email": "fatraaldino@gmail.com",
    "password": "password",
}
##########################################################
# GET UUID
##########################################################
GET http://127.0.0.1:5000/users/30721091
##########################################################
# UPDATE USER
##########################################################
PUT http://127.0.0.1:5000/users/30721099
Content-Type: application/json

{
    "name": "fatrald",
    "email": "caca@gmail.com",
    "password": "tsubasaozora",
    "telp": "0896547885",
    "company": "rsud kariadi semarang"
}

